export const mockFlockData = [
  {
    id: "PAR-001",
    galpon: 1,
    birds: 4850,
    age: 24,
    weight: 1650.5,
    mortality: 3.0,
    production: 87.5,
  },
  {
    id: "PAR-002",
    galpon: 2,
    birds: 4875,
    age: 22,
    weight: 1580.2,
    mortality: 2.5,
    production: 85.2,
  },
  {
    id: "PAR-003",
    galpon: 3,
    birds: 4825,
    age: 26,
    weight: 1720.8,
    mortality: 3.5,
    production: 89.1,
  },
  {
    id: "PAR-004",
    galpon: 4,
    birds: 4900,
    age: 20,
    weight: 1450.3,
    mortality: 2.0,
    production: 86.3,
  },
]

export const mockIoTData = [
  {
    id: 1,
    galponId: 1,
    sensor: "temperature",
    name: "Temperatura",
    value: 24.5,
    unit: "°C",
    status: "normal",
    min: 18,
    max: 28,
  },
  {
    id: 2,
    galponId: 1,
    sensor: "humidity",
    name: "Humedad",
    value: 65.2,
    unit: "%",
    status: "normal",
    min: 40,
    max: 70,
  },
  {
    id: 3,
    galponId: 1,
    sensor: "water",
    name: "Consumo de Agua",
    value: 245.8,
    unit: "L/día",
    status: "normal",
    min: 200,
    max: 300,
  },
  {
    id: 4,
    galponId: 1,
    sensor: "feed",
    name: "Consumo de Alimento",
    value: 125.4,
    unit: "kg/día",
    status: "normal",
    min: 100,
    max: 150,
  },
  // Repeat for other galpones with slight variations
  {
    id: 5,
    galponId: 2,
    sensor: "temperature",
    name: "Temperatura",
    value: 26.8,
    unit: "°C",
    status: "warning",
    min: 18,
    max: 28,
  },
  {
    id: 6,
    galponId: 2,
    sensor: "humidity",
    name: "Humedad",
    value: 58.7,
    unit: "%",
    status: "normal",
    min: 40,
    max: 70,
  },
  {
    id: 7,
    galponId: 2,
    sensor: "water",
    name: "Consumo de Agua",
    value: 238.2,
    unit: "L/día",
    status: "normal",
    min: 200,
    max: 300,
  },
  {
    id: 8,
    galponId: 2,
    sensor: "feed",
    name: "Consumo de Alimento",
    value: 132.1,
    unit: "kg/día",
    status: "normal",
    min: 100,
    max: 150,
  },
  {
    id: 9,
    galponId: 3,
    sensor: "temperature",
    name: "Temperatura",
    value: 23.2,
    unit: "°C",
    status: "normal",
    min: 18,
    max: 28,
  },
  {
    id: 10,
    galponId: 3,
    sensor: "humidity",
    name: "Humedad",
    value: 72.4,
    unit: "%",
    status: "warning",
    min: 40,
    max: 70,
  },
  {
    id: 11,
    galponId: 3,
    sensor: "water",
    name: "Consumo de Agua",
    value: 252.6,
    unit: "L/día",
    status: "normal",
    min: 200,
    max: 300,
  },
  {
    id: 12,
    galponId: 3,
    sensor: "feed",
    name: "Consumo de Alimento",
    value: 118.9,
    unit: "kg/día",
    status: "normal",
    min: 100,
    max: 150,
  },
  {
    id: 13,
    galponId: 4,
    sensor: "temperature",
    name: "Temperatura",
    value: 25.1,
    unit: "°C",
    status: "normal",
    min: 18,
    max: 28,
  },
  {
    id: 14,
    galponId: 4,
    sensor: "humidity",
    name: "Humedad",
    value: 61.8,
    unit: "%",
    status: "normal",
    min: 40,
    max: 70,
  },
  {
    id: 15,
    galponId: 4,
    sensor: "water",
    name: "Consumo de Agua",
    value: 241.3,
    unit: "L/día",
    status: "normal",
    min: 200,
    max: 300,
  },
  {
    id: 16,
    galponId: 4,
    sensor: "feed",
    name: "Consumo de Alimento",
    value: 128.7,
    unit: "kg/día",
    status: "normal",
    min: 100,
    max: 150,
  },
]
